/*----------------------------------------------------------
MASV: 19127424
HO TEN: TRIEU NGUYEN MINH HUY
LAB: 03
NGAY: 14/42022
----------------------------------------------------------*/
-- CAU LENH TAO DB
CREATE DATABASE QLSV

/*----------------------------------------------------------
MASV:19127424
HO TEN: TRIEU NGUYEN MINH HUY
LAB: 03
NGAY: 14/4/2022
----------------------------------------------------------*/
-- CAC CAU LENH TAO TABLE
GO
USE QLSV
GO
CREATE TABLE SINHVIEN
(
	MASV NVARCHAR(20) primary key,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL,
)

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20) primary key,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL,
)
CREATE TABLE LOP
(
	MALOP VARCHAR(20) PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20),
)
GO
/*----------------------------------------------------------
MASV: 19127424
HO TEN: TRIEU NGUYEN MINH HUY
LAB: 03
NGAY: 14/4/2022
----------------------------------------------------------*/
-- CAC CAU LENH TAO STORED PROCEDURE
IF NOT EXISTS
(
SELECT *
FROM SYS.symmetric_keys
WHERE symmetric_key_id=101
)
CREATE MASTER KEY ENCRYPTION BY
	PASSWORD ='19127424'
GO

IF NOT EXISTS
(
	SELECT *
	FROM SYS.certificates
	WHERE NAME= 'MyCert'
)
CREATE CERTIFICATE MYCERT
	WITH SUBJECT = 'MyCert';
GO

IF NOT EXISTS
(
	SELECT	*
	FROM SYS.symmetric_keys
	WHERE NAME='PriKey'
)
CREATE SYMMETRIC KEY PriKey
	WITH ALGORITHM = AES_256
	ENCRYPTION BY CERTIFICATE MyCert;
GO

OPEN SYMMETRIC KEY PriKey
DECRYPTION BY CERTIFICATE MyCert;
GO

CREATE PROCEDURE SP_INS_SINHVIEN 
( --DANH SACH THAM SO
	@MASV NVARCHAR(20), 
	@HOTEN NVARCHAR(100), 
	@NGAYSINH DATETIME, 
	@DIACHI NVARCHAR(200),
	@MALOP VARCHAR(20),
	@TENDN NVARCHAR(100), 
	@MATKHAU VARCHAR(MAX)
)
AS
BEGIN
	INSERT INTO SINHVIEN (MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU)
	VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, HASHBYTES('MD5',@MATKHAU))
END;
GO

CREATE PROCEDURE SP_INS_NHANVIEN
( --DANH SACH THAM SO
	@MANV VARCHAR(20),
	@HOTEN NVARCHAR(100),
	@EMAIL VARCHAR(20),
	@LUONG INT,
	@TENDN NVARCHAR(100),
	@MATKHAU VARCHAR(MAX)
)
AS
BEGIN
	INSERT INTO NHANVIEN
	VALUES (@MANV, @HOTEN, @EMAIL, EncryptByKey(Key_GUID('PriKey'), CONVERT(VARCHAR(MAX), @LUONG)), @TENDN, HASHBYTES('SHA1', @MATKHAU))
END;
GO

CREATE PROCEDURE SP_SEL_NHANVIEN
AS
BEGIN
    SELECT MANV,HOTEN, EMAIL,CONVERT(VARCHAR(MAX),DECRYPTBYKEY(LUONG)) AS LUONGCB FROM NHANVIEN
END;
GO

EXEC SP_INS_SINHVIEN 'SV01', 'NGUYEN VAN A', '1/1/1990', '280 AN DUONG VUONG', 'CNTT-K35', 'NVA', '123456'
GO

EXEC SP_INS_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@', 3000000,'NVA', 'abcd12'
GO

EXEC SP_SEL_NHANVIEN