/*----------------------------------------------------------
MASV:
19127424
19127509
HO TEN CAC THANH VIEN NHOM:
Triệu Nguyễn Minh Huy
Trương Thế Phú
LAB: 03 - NHOM
NGAY: 22/04/2022
----------------------------------------------------------*/
/*CAU LENH TAO DB*/
CREATE DATABASE QLSVNhom
GO
/*----------------------------------------------------------
MASV:
19127424
19127509
HO TEN CAC THANH VIEN NHOM:
Triệu Nguyễn Minh Huy
Trương Thế Phú
LAB: 03 - NHOM
NGAY: 22/04/2022
----------------------------------------------------------*/
/*CAU LENH TAO TABLE*/
USE QLSVNhom
GO

CREATE TABLE SINHVIEN 
(
    MASV VARCHAR(20),
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATETIME,
    DIACHI NVARCHAR(200),
    MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT	NULL,
    MATKHAU VARBINARY(MAX) NOT NULL,
	PRIMARY KEY (MASV)
);
GO

CREATE TABLE NHANVIEN 
(
    MANV VARCHAR(20),
    HOTEN NVARCHAR(100) NOT NULL,
    EMAIL VARCHAR(20),
    LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT	NULL,
    MATKHAU VARBINARY(MAX) NOT NULL,
	PUBKEY VARCHAR(20),
	PRIMARY KEY (MANV)
);
GO

CREATE TABLE LOP 
(
    MALOP VARCHAR(20),
    TENLOP NVARCHAR(100) NOT NULL,
    MANV VARCHAR(20),
	PRIMARY KEY (MALOP)
);
GO

CREATE TABLE HOCPHAN 
(
    MAHP VARCHAR(20),
    TENHP NVARCHAR(100) NOT NULL,
    SOTC INT,
	PRIMARY KEY (MAHP)
);
GO

CREATE TABLE BANGDIEM 
(
    MASV VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES SINHVIEN(MASV),
    MAHP VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES HOCPHAN(MAHP),
    DIEMTHI VARBINARY(MAX)
);
GO
/*----------------------------------------------------------
MASV:
19127424
19127509
HO TEN CAC THANH VIEN NHOM:
Triệu Nguyễn Minh Huy
Trương Thế Phú
LAB: 03 - NHOM
NGAY: 22/04/2022
----------------------------------------------------------*/
/*CAU LENH TAO STORED PROCEDURE*/

IF NOT EXISTS
(
SELECT *
FROM SYS.symmetric_keys
WHERE symmetric_key_id=101
)
CREATE MASTER KEY ENCRYPTION BY
	PASSWORD ='19127509'
GO

IF NOT EXISTS
(
	SELECT *
	FROM SYS.certificates
	WHERE NAME= 'MyCert'
)
CREATE CERTIFICATE MYCERT
	WITH SUBJECT = 'MyCert';
GO

IF NOT EXISTS
(
	SELECT	*
	FROM SYS.asymmetric_keys
	WHERE NAME='AKey'
)
CREATE ASYMMETRIC KEY AKey
	WITH ALGORITHM = RSA_512
	ENCRYPTION BY PASSWORD = 'NV1';
GO

CREATE PROCEDURE SP_INS_PUBLIC_NHANVIEN
(@MANV VARCHAR(20), @HOTEN NVARCHAR(100), @EMAIL VARCHAR(20), @LUONGCB INT,
 @TENDN NVARCHAR(100), @MK VARCHAR(MAX))
 AS
 BEGIN
	INSERT INTO NHANVIEN
	VALUES (@MANV,@HOTEN,@EMAIL,ENCRYPTBYASYMKEY(ASYMKEY_ID('AKey'),CONVERT(VARCHAR(MAX),@LUONGCB)),@TENDN,HASHBYTES('SHA1',@MK),'NV01')
 END
 GO

EXEC SP_INS_PUBLIC_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@', 3000000, 'NVA', 'abcd12'
GO

CREATE PROCEDURE SP_SEL_PUBLIC_NHANVIEN
(@TENDN NVARCHAR(100), @MK VARCHAR(MAX))
AS
BEGIN
    SELECT MANV,HOTEN, EMAIL,CONVERT(VARCHAR(MAX),DECRYPTBYASYMKEY(ASYMKEY_ID('AKey'),LUONG)) AS LUONGCB FROM NHANVIEN
	WHERE TENDN=@TENDN AND MATKHAU=HASHBYTES('SHA1',@MK)
END
GO

EXEC SP_SEL_PUBLIC_NHANVIEN 'NVA', 'abcd12'
